name: 'Packer Build - Windows Server 2022'

# Allow run manually
on:
  workflow_dispatch:
    inputs:
      packer_code_location:
        type: string
        description: What working directory should be passed to the script
        default: "packer/windows/windows-server2022-azure"
      packer_version:
        type: string
        description: 'What version of packer to attempt to use?'
        default: default
      run_packer_init:
        type: boolean
        description: 'Whether Packer init should be ran'
        default: true
      run_packer_build:
        type: boolean
        description: 'Whether Packer build should be ran'
        default: true
      run_packer_validate:
        type: boolean
        description: 'Whether Packer validate should be ran'
        default: true
      packer_file_name:
        type: string
        description: 'Packer file name'
        default: 'packer.pkr.hcl'
      add_client_to_nsg:
        type: boolean
        description: 'Whether to add your outbound client IP to an NSG'
        default: true
      nsg_resource_id:
        type: string
        description: 'NSG resource ID if you want to add a NSG rule'

jobs:
  run-script:
    name: 'Run Script'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pkenv
        id: install-pkenv
        shell: pwsh
        run: |
          brew tap kwilczynski/homebrew-pkenv
          brew install pkenv

      - name: Install PowerShell modules
        id: install-powershell-modules
        shell: pwsh
        run: |
          pwsh -Command Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted ; `
          pwsh -Command Install-Module -Name Az.Accounts -Force -AllowClobber -Scope CurrentUser -Repository PSGallery ; `
          pwsh -Command Install-Module -Name Az.Network -Force -AllowClobber -Scope CurrentUser -Repository PSGallery ; `
          pwsh -Command Install-Module -Name Az.Storage -Force -AllowClobber -Scope CurrentUser -Repository PSGallery 

      - name: Build
        id: run-script
        shell: pwsh
        run: |
          
          .\Run-Packer.ps1 `
            -WorkingDirectory ${{ inputs.packer_code_location }} `
            -RunPackerInit ${{ inputs.run_packer_init }} `
            -RunPackerValidate ${{ inputs.run_packer_validate }} `
            -AddCurrentClientToNsg ${{ inputs.add_client_to_nsg }} `
            -NsgResourceId ${{ vars.nsgid }}
        env:
          PKR_VAR_ARM_CLIENT_ID: ${{ secrets.SpokeSvpApplicationId }}
          PKR_VAR_ARM_CLIENT_SECRET: ${{ secrets.SpokeSvpClientSecret }}
          PKR_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.SpokeSubscriptionId }}
          PKR_VAR_ARM_TENANT_ID: ${{ secrets.SpokeSvpTenantId }}
